version: '3.0'

services:
  sshportal:
    image: moul/sshportal
    environment:
      - SSHPORTAL_DEFAULT_ADMIN_INVITE_TOKEN=integration
    command: server --debug
    depends_on:
      - testserver
    ports:
      - 2222

  testserver:
    image: moul/sshportal
    command: _test_server
    ports:
      - 2222

  client:
    build: .
    depends_on:
      - sshportal
      - testserver
    #volumes:
    #  - .:/integration
    tty: true
